name             'cook_php'
maintainer       'Mercicc'
maintainer_email 'chouandy625@gmail.com'
license          'All rights reserved'
description      'Installs PHP development environment'
version          '1.0.0'

depends 'apt'
depends 'curl'
depends 'git'
depends 'nodejs'
depends 'nginx'
depends 'apache2'
depends 'php'
depends 'php-fpm'
depends 'mysql'
