name             'cook_php'
maintainer       'Mercicc'
maintainer_email 'chouandy625@gmail.com'
license          'All rights reserved'
description      'Installs PHP development environment'
version          '0.1.0'

depends 'selinux'
depends 'apt'
depends 'curl'
depends 'git'
depends 'nodejs'
depends 'apache2'
depends 'iptables'
depends 'mysql2_chef_gem'
depends 'mysql'
depends 'database'
depends 'php'
depends 'php-fpm'
